version: '3.1'
services:

  statistic:
    build: ./statistic
    image: ewm-stats-image
    container_name: ewm-stats-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=stat
      - SPRING_DATASOURCE_PASSWORD=777777

  stats-db:
    image: postgres:14-alpine
    container_name: postgre-ewm-stats
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=777777

  major:
    build: ./major
    image: ewm-major-image
    container_name: ewm-major-container
    ports:
      - "8080:8080"
    depends_on:
      - major-db
      - statistic
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://major-db:5432/ewm-major
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=228228
      - STATS-SERVER_URL=http://stats-server:9090

  major-db:
    image: postgres:14-alpine
    container_name: postgre-ewm-major
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=ewm-major
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=228228