CREATE TABLE IF NOT EXISTS statistics
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(128)                            NOT NULL,
    uri       VARCHAR(256)                            NOT NULL,
    ip        VARCHAR(256)                            NOT NULL,
    timestamp VARCHAR(32)                             NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id)
);
